### ISSUE TITLE
does not build with 0.1.4 jdk8 on OSX

### ISSUE THREAD

**Issue by johnynek** [avibryant/bazel-scala-example#1]
```
st-oscar1:bazel-scala-example oscar$ bazel test example-lib:test
.....
INFO: Elapsed time: 0.466s
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at com.google.devtools.build.lib.bazel.repository.GitCloner.clone(GitCloner.java:139)
        at com.google.devtools.build.lib.bazel.repository.GitRepositoryFunction.fetch(GitRepositoryFunction.java:45)
        at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:125)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.JSchException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more
```

```
st-oscar1:bazel-scala-example oscar$ bazel 
.....
                                                           [bazel release 0.1.4]
```

**Comment by johnynek** [comment]
Work around:

comment out:

```
#[url "git@github.com:"]
#       insteadOf = https://github.com/
```

in `~/.gitconfig`

after the first pull you can reset

**Comment by johnynek** [comment]
Fixed here: https://github.com/bazelbuild/bazel/issues/802#issuecomment-174059580

but not released in `0.1.4`.
